name:                WiLaun
version:             0.1.0.0
github:              "WizardNG/WiLaun"
license:             BSD3
author:              "Kozlov Yury"
maintainer:          "wizardng1@gmail.com"
copyright:           "home"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WizardNG/WiLaun#readme>

dependencies:
- base 
- unix
- libiserv
- ghc
- filepath
- directory
- extra
- aeson

library:
  source-dirs: src

executables:
  WiLaun-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # All packages
    - -Wall
    - -Werror
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WiLaun

tests:
  WiLaun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WiLaun
